const PRODUCTS_INIT = 'PRODUCTS_INIT'
const MSGS_INIT = 'MSGS_INIT'
const POST_PRODUCT = 'POST_PRODUCT'
const NEW_PRODUCT = 'NEW_PRODUCT'
const POST_MESSAGE = 'POST_MESSAGE'
const NEW_MESSAGE = 'NEW_MESSAGE'
const TEST_INIT = 'TEST_INIT'

module.exports = {
    PRODUCTS_INIT,
    MSGS_INIT,
    POST_PRODUCT,
    NEW_PRODUCT,
    POST_MESSAGE,
    NEW_MESSAGE,
    TEST_INIT
}